export const SCREENSHOTSBYTIME_TASK = 'SCREENSHOTSBYTIME_TASK';
export const VIDEOSBYTIME_TASK = 'VIDEOSBYTIME_TASK';

export const CREATE_SCREENSHOT = 'CREATE_SCREENSHOT';
export const CREATE_VIDEO = 'CREATE_VIDEO';
export const IMAGE_VIEWER = 'IMAGE_VIEWER';

export const CREATE_CAMERA = 'CREATE_CAMERA';
export const EDIT_CAMERA = 'EDIT_CAMERA';
export const DELETE_CAMERA = 'DELETE_CAMERA';
