export const EDIT_SCREENSHOTSBYTIME_SETTINGS = 'EDIT_SCREENSHOTS_SETTINGS';
export const EDIT_VIDEOSBYTIME_SETTINGS = 'EDIT_VIDEOS_SETTINGS';

export const CREATE_VIDEO = 'CREATE_VIDEO';
export const IMAGE_VIEWER = 'IMAGE_VIEWER';

export const ADD_CAMERA = 'ADD_CAMERA';
export const EDIT_CAMERA = 'EDIT_CAMERA';
